# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos-docker"
  config.vm.box_url = "centos-docker.box"
  config.vm.network "forwarded_port", guest: 80, host: 8080
end